name: Application Compatibility Test

on:
  push:
  workflow_dispatch:

jobs:
  test-on-ubuntu:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

  test-on-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test